### ISSUE TITLE
Login button not working then nothing syncs

### ISSUE THREAD

**Issue by darkjenso** [IronMooseDevelopment/FoundryVTT-dScryb-public#17]
So i seem to be getting this error with multiple versions of the module. I try to log in, nothing changes, i reload the world to see i am logged in but nothing with sync. 

when i try to sync manually, this error comes up in the console

game:1 Access to fetch at 'https://dscryb.com/wp-json/jwt-auth/v1/scene?per_page=1&_fields=id' from origin '[my ip]' has been blocked by CORS policy: Request header field x-pagely-skip-ratelimit is not allowed by Access-Control-Allow-Headers in preflight response.Understand this error
dscrybApi.mjs:744 
        
        
       GET https://dscryb.com/wp-json/jwt-auth/v1/scene?per_page=1&_fields=id net::ERR_FAILED
_fetch @ dscrybApi.mjs:744
determineBasePath @ dscrybApi.mjs:320
loadUserInfo @ dscrybApi.mjs:378
sync @ dscrybManager.mjs:135
_updateObject @ CategorySelectionApp.mjs:56
await in _updateObject
_onSubmit @ foundry.js:6665Understand this error
dscrybApi.mjs:744 
        
        
       
        
       Uncaught (in promise) TypeError: Failed to fetch
[Detected 1 package: dscryb(5.0.0)]
    at dscrybApi._fetch (dscrybApi.mjs:744:26)
    at dscrybApi.determineBasePath (dscrybApi.mjs:320:35)
    at dscrybApi.loadUserInfo (dscrybApi.mjs:378:20)
    at dscrybManager.sync (dscrybManager.mjs:135:42)
    at CategorySelectionApp._updateObject (CategorySelectionApp.mjs:56:32)
    at async CategorySelectionApp._onSubmit (foundry.js:6665:7)

**Comment by michal-a** [comment]
Looks like dscryb.com changed the CORS policy, which broke the module. I have exactly the same issue.

The dirty temporary workaround is to open developer console (F12) and in error log click on the line dscrybApi.mjs:744:26
Then just remove this part of the line in fetch
![Screenshot from 2024-09-24 17-50-10](https://github.com/user-attachments/assets/b7d13601-be2c-4db1-8c21-8ec2f816c052)
`'X-Pagely-Skip-Ratelimit': this.debug ? 'a98301c8664cce5c62f249d349b02370' : '291d3786deb9c92c6c324cc35868ee1c'`

**Comment by pervandyke** [comment]
Having a similar issue, but it's on a call to https://dscryb.azurewebsites.net/api/GetActiveMemberships?code=***
The actual error that pops up is

>  Server error while getting Active Memberships. Please try again later.

**Comment by Arcainne** [comment]
Also seeing this CORS issue when trying to login.

![image](https://github.com/user-attachments/assets/3b634d7b-98d7-4e8a-9293-43858bc67d6e)

I just bought a dScryb membership for the first time specifically to use this module. :( I'll probably need to cancel until this gets resolved.

**Comment by joshuafinch** [comment]
Same issue here: 
![image](https://github.com/user-attachments/assets/72497ff8-ff4c-4197-9d3e-b5b23258df32)

**Comment by rdot89** [comment]
Same Issue on my end. Tested on both Dscryb 4.4.3 and 5.0, as well as DnD5e 3.3.1 and 4.0.4
FoundryVTT v12.331
![image](https://github.com/user-attachments/assets/dd0d2304-ace0-419b-9aa9-f5b8ee83ebf3)

**Comment by rdot89** [comment]
Just going to post this here for non-discord users to be aware: devs are currently looking into the situation and aiming for a resolution ASAP... there have identified the issue and working out the kinks to avoid whole-server issues:/crashes for foundry syncing AND Opus website users:
![image](https://github.com/user-attachments/assets/7cca5a54-810f-4395-92ae-500cd4f92432)

**Comment by rdot89** [comment]
Minor update, looks like a fix is moving along nicely:
![image](https://github.com/user-attachments/assets/50d95b04-bb28-4de6-ade9-f833c58f8ea7)

**Comment by rdot89** [comment]
An update to the current issue for you all:
Dscryb OPUS is now live, as part of the latest Module update (5.0.2)
Heres a final summary of the issue ancd actions taken:
![image](https://github.com/user-attachments/assets/a5957f2b-ffbf-4e07-8c59-87f4d76c8bd4)
Note that this only resolves the audio library/streaming side of things... Maps and other features will be getting resolved asap:
![image](https://github.com/user-attachments/assets/2b7e2ab9-da5d-4082-9ce6-0f3098791a0c)

Another thing to be mindful of: if you update the module via Foundry's auto update buttone, or hot the update button (that looks like thr refresh icon) on the actual module itself, it may attempt to downgrade you to 4.4.4... If this happens:
1. Uninstall the Dscryb module
2. Re-install the module (via foundry moulde search or using copy-pasting the json link from github)
3. open your world and disble to module in module management, then restart the server and re-enable it.

**Comment by Arcainne** [comment]
I can confirm that it works now! Thank you for the update! 🎉
